image: Ubuntu1804

environment:
  matrix:
    - nodejs_version: '14'
install:
  - sudo apt install gnupg ca-certificates
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - echo "deb https://download.mono-project.com/repo/ubuntu stable-bionic/snapshots/6.10 main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
  - sudo apt update
  - sudo apt install fsharp=4.5-0xamarin12+ubuntu1804b1 -y
  - nvm install --lts
  - npm config set @zen:registry https://www.myget.org/F/zenprotocol/npm/
  - npm install @zen/zebra -g

build: off
shallow_clone: true
matrix:
  # stop build on first failure
  fast_finish: true

test_script:
  - sh run-test.sh